# Generated by Django 3.0.2 on 2020-01-08 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='created',
        ),
        migrations.AddField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Auction Close Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
    ]
