# Generated by Django 3.0.2 on 2020-01-09 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200108_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='auction',
        ),
        migrations.AddField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.Item'),
        ),
    ]
