# Generated by Django 3.0.2 on 2020-01-09 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200109_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Item'),
        ),
    ]
