# Generated by Django 3.0.2 on 2020-01-10 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200109_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this page. Generated by the system.', max_length=600),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(verbose_name='Auction Close Date and Time: format YYYY-MM-DD HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Item'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date and Time: format YYYY-MM-DD HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
