# Generated by Django 3.0.2 on 2020-01-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_auction_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='items',
            field=models.ManyToManyField(to='auctions.Item'),
        ),
    ]
