# Generated by Django 3.0.2 on 2020-01-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(verbose_name='Auction Close Date and Time: format YYYY-MM-DD HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date and Time: format YYYY-MM-DD HH:MM:SS'),
        ),
    ]
